flowchart LR
    A1[Usuario Plataforma]
    A2[Dispositivo]

    subgraph Modulo Analitico
        UC1([Consultar Linea de Tiempo de Eventos])
        UC2([Reproducir Evidencia Multimedia])
        UC3([Ver Metricas de Comportamiento])
        UC4([Generar Resumen Descriptivo con IA])
        UC5([Descargar Reporte Consolidado])
        UC6([Recibir Notificacion Critica In-App])
    end

    A1 --> UC1
    A1 --> UC2
    A1 --> UC3
    A1 --> UC4
    A1 --> UC5
    UC6 -->|Lee Notificacion| A1

    A2 -->|Dispara Evento Critico| UC6